# TokenReview Create ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.installation.namespace }}
  name: token-review-creator
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
# bind the role to polaris-security
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-token-review
  namespace: {{ .Values.installation.namespace }}
subjects:
- kind: ServiceAccount
  name: polaris-security # "name" is case sensitive
  namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: ClusterRole
  name: token-review-creator
  apiGroup: rbac.authorization.k8s.io