---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: polaris-security
  namespace: {{ .Values.installation.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: polaris-security
  namespace: {{ .Values.installation.namespace }}
  labels:
    app: polaris-security
spec:
  selector:
    app: polaris-security
  ports:
    - name: polaris-security-port
      protocol: TCP
      port: {{ .Values.polaris_security.port }}
      targetPort: {{ .Values.polaris_security.port }}